apiVersion: v1
kind: Pod
metadata:
  name: wbsrivaldo
  labels:
    name: wbsrivaldo
    year: '2024'
spec:
  containers:
  - name: wbsrivaldo
    image: nginx:1.27.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
        - containerPort: 80